name: cmake_testing_win

on:
  push:
    branches: [ "master", "more_data_on_meta_instance_creation", "algorithm_whole_test" ]
  pull_request:
    branches: [ "master", "more_data_on_meta_instance_creation", "algorithm_whole_test" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    
    - name : Restore solver cache
      id : cache-HIGHS
      uses : actions/cache@v3
      env :
        cache-name : cache-HIGHS-installation
      with :
        key : ${{ runner.os }}-${{ env.cache-name }}
        path : ${{ github.workspace }}/HiGHS

    - if : ${{ steps.cache-HIGHS.outputs.cache-hit != 'true' }}
      uses: actions/checkout@v3
      with:
        repository: ERGO-Code/HiGHS
        path: HiGHS

    - if : ${{ steps.cache-HIGHS.outputs.cache-hit != 'true' }}
      name: Build solver with cmake
      uses: lukka/run-cmake@v3
      with:
        cmakeListsTxtPath: '${{ github.workspace }}/HiGHS/CMakeLists.txt'
        cmakeAppendedArgs: '-D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache -D CMAKE_BUILD_TYPE=Release'
        buildWithCMake: true
        buildDirectory: '${{ github.workspace }}/HiGHS/build'

    - uses: actions/checkout@v3
      with:
        path: main

    - name: Build with cmake
      uses: lukka/run-cmake@v3
      with:
        cmakeListsTxtPath: '${{ github.workspace }}/main/CMakeLists.txt'
        cmakeAppendedArgs: '-D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache -D CMAKE_BUILD_TYPE=Debug -D BUILD_TESTING=true -D TEST_SOLVER_USING_TESTS=true -DHIGHS_SOURCE_DIR=${{ github.workspace }}'
        buildWithCMake: true
        buildDirectory: '${{ github.workspace }}/main/build'
        
    - name : Test
      shell : bash
      working-directory: ${{github.workspace}}/main/build
      run : |
        ctest
