name: cmake_testing_win

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest, macos-latest

    steps:
    
    - uses: actions/checkout@v3

    - name: Build with cmake
      uses: lukka/run-cmake@v3
      with:
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        cmakeAppendedArgs: '-D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache'
        buildWithCMake: true
        buildDirectory: '${{ github.workspace }}/build'
        
    - name : Test
      shell : bash
      working-directory: ${{github.workspace}}/build
      run : |
        ctest
