# This is a basic workflow to help you get started with Actions

name: cmake_testing

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master", "algorithm_whole_test" ]
  pull_request:
    branches: [ "master", "algorithm_whole_test" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name : Install deps
        run : |
          sudo apt update
          sudo apt install python3
          sudo apt install cmake

      - name : Restore solver cache
        id : cache-HIGHS
        uses : actions/cache@v3
        env :
          cache-name : cache-HIGHS-installation
        with :
          key : ${{ runner.os }}-${{ env.cache-name }}
          path : ~/HiGHS

      - if : ${{ steps.cache-HIGHS.outputs.cache-hit != 'true' }}
        name : Prepare solver
        continue-on-error : true
        run : |
          cd ~
          git clone https://github.com/ERGO-Code/HiGHS.git
          cd HiGHS
          mkdir build
          cd build
          cmake ..
          cmake --build .
          sudo cmake --install .
          

      # Runs a set of commands using the runners shell
      - name: Build and Test
        continue-on-error : true
        run: |
          mkdir build
          cd build
          cmake -DTEST_SOLVER_USING_TESTS=true ..
          make
          ctest
